### ISSUE TITLE
Send on closed channel

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/sdp-go#15]
```
panic: send on closed channel

goroutine 9157 [running]:
github.com/overmindtech/sdp-go.(*RequestProgress).Start.func1(0xc002143cc0)
	/workspace/vendor/github.com/overmindtech/sdp-go/progress.go:328 +0xdf
reflect.Value.call({0xdaec20, 0xc001651630, 0x13}, {0xea0709, 0x4}, {0xc000015de8, 0x1, 0x1})
	/usr/local/go/src/reflect/value.go:556 +0xc16
reflect.Value.Call({0xdaec20, 0xc001651630, 0x13}, {0xc000015de8, 0x1, 0x1})
	/usr/local/go/src/reflect/value.go:339 +0xb7
github.com/nats-io/nats%2ego.(*EncodedConn).subscribe.func1(0xc0009fd3e0)
	/workspace/vendor/github.com/nats-io/nats.go/enc.go:234 +0x825
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc000322000, 0xc002072d00)
	/workspace/vendor/github.com/nats-io/nats.go/nats.go:2715 +0x3bc
created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked
	/workspace/vendor/github.com/nats-io/nats.go/nats.go:3933 +0x6d6
```

**Comment by dylanratcliffe** [comment]
I got this while testing another project but I can't replicate it reliably...

**Comment by dylanratcliffe** [comment]
I've had it happen again but once again I can't replicate it. However I can confirm that I'm definitely not closing the channel outside if this library. It must still be possible to bypass the protections I've put in place. Would be good if I could replicate it in a test

**Comment by dylanratcliffe** [comment]
The channel that is closed is `rp.itemChan`

```go
rp.itemSub, err = natsConnection.Subscribe(rp.Request.ItemSubject, func(item *Item) {
    if item != nil {
        rp.chanMutex.RLock()
        defer rp.chanMutex.RUnlock()
        
        rp.itemChan <- item
    }
})
```

**Comment by dylanratcliffe** [comment]
This is still possible in `v0.13.2`. I'll try to get a stacktrace

**Comment by dylanratcliffe** [comment]
I've seen this in `gateway` under heavy load but once again forgot to get the stacktrace

**Comment by dylanratcliffe** [comment]
Latest stacktrace:

```
panic: send on closed channel

goroutine 90 [running]:
github.com/overmindtech/sdp-go.(*RequestProgress).Start.func1(0xc000444aa0)
        /go/pkg/mod/github.com/overmindtech/sdp-go@v0.14.0/progress.go:421 +0x308
reflect.Value.call({0x9cda20?, 0xc000177ab0?, 0xc000444aa0?}, {0xa9c010, 0x4}, {0xc000325e38, 0x1, 0xa7a420?})
        /usr/local/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0x9cda20?, 0xc000177ab0?, 0x45f15b?}, {0xc000325e38, 0x1, 0x1})
        /usr/local/go/src/reflect/value.go:339 +0xbf
github.com/nats-io/nats%2ego.(*EncodedConn).subscribe.func1(0xc000446ee0?)
        /go/pkg/mod/github.com/nats-io/nats.go@v1.20.0/enc.go:234 +0x707
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc0003ef800, 0xc000175ee0)
        /go/pkg/mod/github.com/nats-io/nats.go@v1.20.0/nats.go:2839 +0x442
created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked
        /go/pkg/mod/github.com/nats-io/nats.go@v1.20.0/nats.go:4069 +0x3f8panic: send on closed channel

goroutine 90 [running]:
github.com/overmindtech/sdp-go.(*RequestProgress).Start.func1(0xc000444aa0)
        /go/pkg/mod/github.com/overmindtech/sdp-go@v0.14.0/progress.go:421 +0x308
reflect.Value.call({0x9cda20?, 0xc000177ab0?, 0xc000444aa0?}, {0xa9c010, 0x4}, {0xc000325e38, 0x1, 0xa7a420?})
        /usr/local/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0x9cda20?, 0xc000177ab0?, 0x45f15b?}, {0xc000325e38, 0x1, 0x1})
        /usr/local/go/src/reflect/value.go:339 +0xbf
github.com/nats-io/nats%2ego.(*EncodedConn).subscribe.func1(0xc000446ee0?)
        /go/pkg/mod/github.com/nats-io/nats.go@v1.20.0/enc.go:234 +0x707
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc0003ef800, 0xc000175ee0)
        /go/pkg/mod/github.com/nats-io/nats.go@v1.20.0/nats.go:2839 +0x442
created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked
        /go/pkg/mod/github.com/nats-io/nats.go@v1.20.0/nats.go:4069 +0x3f8
```

**Comment by dylanratcliffe** [comment]
Newer:

```
panic: send on closed channel [recovered]
        panic: send on closed channel

goroutine 316 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
        /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.11.2/trace/span.go:383 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00086fb00, {0x0, 0x0, 0x5?})
        /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.11.2/trace/span.go:421 +0x93b
panic({0xcf2740, 0x10d2210})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/overmindtech/sdp-go.(*RequestProgress).Start.func1({0x10da7a8?, 0xc0008ce420?}, 0xc000312140)
        /go/pkg/mod/github.com/overmindtech/sdp-go@v0.15.0/progress.go:404 +0x308
github.com/overmindtech/sdp-go.NewItemHandler.func1({0x10da7a8, 0xc0008ce420}, 0xc0002c8230)
        /go/pkg/mod/github.com/overmindtech/sdp-go@v0.15.0/handler_item.go:19 +0x96
github.com/overmindtech/sdp-go.NewOtelExtractingHandler.func1(0x0?)
        /go/pkg/mod/github.com/overmindtech/sdp-go@v0.15.0/tracing.go:40 +0x12f
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc00017c000, 0xc000894b60)
        /go/pkg/mod/github.com/nats-io/nats.go@v1.22.1/nats.go:2934 +0x442
created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked
        /go/pkg/mod/github.com/nats-io/nats.go@v1.22.1/nats.go:4164 +0x3f8
```

**Comment by dylanratcliffe** [comment]
This seems to have gotten worse with https://github.com/overmindtech/discovery/releases/tag/v0.21.6
